"""drako comply — EU AI Act documentation generator (optional extra).

This package builds the ComplianceContext from a project's scan output,
BOM, runtime config, and a guided questionnaire, then renders Article 9,
11, 12, and 14 documents in DOCX and PDF format. Heavy dependencies
(python-docx, weasyprint, jinja2) are imported lazily inside the
generators so a bare `pip install drako` never breaks the CLI.
"""

from drako.comply.mapping import ComplianceContext, build_context

__all__ = ["ComplianceContext", "build_context"]

# Mandatory legal disclaimer prepended to every generated document. Must
# never be removable, optional, or suppressible.
LEGAL_DISCLAIMER = (
    "LEGAL DISCLAIMER: This document is automatically generated by Drako from the "
    "outputs of a technical scan, a Bill of Materials, audit trail data, and a "
    "user-provided questionnaire. It is intended as a DRAFT that MUST be reviewed "
    "by qualified legal counsel before submission to any regulatory authority or "
    "use in any compliance context. Drako does not provide legal advice. The "
    "accuracy, completeness, and legal sufficiency of this document are the sole "
    "responsibility of the deploying organization."
)
