"""`agentmesh init` — Initialize AgentMesh in an existing project."""

from __future__ import annotations

import os
import textwrap
from pathlib import Path

import click
import yaml

from agentmesh.utils.detection import detect_framework

_CONFIG_FILENAME = ".agentmesh.yaml"


# ------------------------------------------------------------------
# Middleware template generators
# ------------------------------------------------------------------

_CREWAI_TEMPLATE = textwrap.dedent("""\
    \"\"\"AgentMesh compliance middleware for CrewAI — generated by `agentmesh init`.\"\"\"
    from agentmesh import with_compliance

    # Wrap your crew with AgentMesh compliance:
    #
    #   from your_crew import MyCrew
    #   from agentmesh_middleware import compliant_crew
    #
    #   crew = MyCrew()
    #   result = compliant_crew(crew).kickoff()

    def compliant_crew(crew, **kwargs):
        return with_compliance(crew, **kwargs)
""")

_LANGGRAPH_TEMPLATE = textwrap.dedent("""\
    \"\"\"AgentMesh compliance middleware for LangGraph — generated by `agentmesh init`.\"\"\"
    from agentmesh import with_langgraph_compliance

    # Wrap your compiled graph with AgentMesh compliance:
    #
    #   from agentmesh_middleware import compliant_graph
    #
    #   graph = compliant_graph(my_graph.compile())
    #   result = graph.invoke(input)

    def compliant_graph(graph, **kwargs):
        return with_langgraph_compliance(graph, **kwargs)
""")

_AUTOGEN_TEMPLATE = textwrap.dedent("""\
    \"\"\"AgentMesh compliance middleware for AutoGen — generated by `agentmesh init`.\"\"\"
    from agentmesh import with_autogen_compliance

    # Add compliance to your AutoGen group chat:
    #
    #   from agentmesh_middleware import compliant_chat
    #
    #   chat = compliant_chat(my_group_chat)

    def compliant_chat(group_chat, **kwargs):
        return with_autogen_compliance(group_chat, **kwargs)
""")

_GENERIC_TEMPLATE = textwrap.dedent("""\
    \"\"\"AgentMesh MCP client example — generated by `agentmesh init`.\"\"\"
    from agentmesh import AgentMeshClient

    # Example: use the AgentMesh client directly
    #
    #   from agentmesh_mcp_client import get_client
    #
    #   client = get_client()
    #   result = client.verify_agent_identity_sync("my-agent", "researcher")

    def get_client(**kwargs):
        return AgentMeshClient.from_config(**kwargs)
""")

_TEMPLATES = {
    "crewai": ("agentmesh_middleware.py", _CREWAI_TEMPLATE),
    "langgraph": ("agentmesh_middleware.py", _LANGGRAPH_TEMPLATE),
    "autogen": ("agentmesh_middleware.py", _AUTOGEN_TEMPLATE),
    "generic": ("agentmesh_mcp_client.py", _GENERIC_TEMPLATE),
}


# ------------------------------------------------------------------
# CLI Command
# ------------------------------------------------------------------

@click.command()
@click.option("--api-key", envvar="AGENTMESH_API_KEY", help="API key (or set AGENTMESH_API_KEY)")
@click.option(
    "--framework",
    type=click.Choice(["crewai", "langgraph", "autogen", "generic"], case_sensitive=False),
    help="Override framework auto-detection",
)
@click.option("--endpoint", default="https://api.useagentmesh.com", help="Custom endpoint for self-hosted")
def init(api_key: str | None, framework: str | None, endpoint: str) -> None:
    """Initialize AgentMesh in your current project."""

    click.echo()
    click.secho("  AgentMesh — The Trust Layer for AI Agents", fg="cyan", bold=True)
    click.echo()

    # ---- Step 1: detect framework ----
    if not framework:
        detected = detect_framework(".")
        if detected:
            framework = detected
            click.echo(click.style("  [detect] ", fg="green") + f"Detected {framework} project")
        else:
            framework = "generic"
            click.echo(click.style("  [detect] ", fg="yellow") + "No specific framework detected. Using generic MCP setup.")
    else:
        click.echo(click.style("  [detect] ", fg="green") + f"Using framework: {framework}")

    # ---- Step 2: get API key ----
    if not api_key:
        env_key = os.environ.get("AGENTMESH_API_KEY")
        if env_key:
            api_key = env_key
            click.echo(click.style("  [auth]   ", fg="green") + "Using API key from AGENTMESH_API_KEY env var")
        else:
            click.echo()
            click.echo("  Get a free API key at: " + click.style("https://app.useagentmesh.com/signup", fg="cyan", underline=True))
            api_key = click.prompt("  Enter your API key", hide_input=False)

    # ---- Step 3: validate API key ----
    click.echo(click.style("  [auth]   ", fg="green") + "Validating API key...")
    try:
        import httpx

        with httpx.Client(timeout=10.0) as http:
            resp = http.get(
                f"{endpoint.rstrip('/')}/api/v1/stats",
                headers={"Authorization": f"Bearer {api_key}"},
            )
        if resp.status_code == 401:
            click.secho("  [error]  Invalid API key. Get one at https://app.useagentmesh.com/signup", fg="red")
            raise SystemExit(1)
        if resp.status_code >= 400:
            click.secho(f"  [warn]   Could not validate key (HTTP {resp.status_code}). Continuing anyway.", fg="yellow")
        else:
            click.echo(click.style("  [auth]   ", fg="green") + "API key validated")
    except httpx.ConnectError:
        click.secho("  [warn]   Could not reach backend. Continuing in offline mode.", fg="yellow")

    # Extract tenant_id from key
    parts = api_key.split("_")
    tenant_id = parts[2] if len(parts) >= 3 else "default"

    # ---- Step 4: check for existing config ----
    config_path = Path(_CONFIG_FILENAME)
    if config_path.exists():
        if not click.confirm(f"\n  {_CONFIG_FILENAME} already exists. Overwrite?", default=False):
            click.echo("  Aborted.")
            return

    # ---- Step 5: generate .agentmesh.yaml ----
    config_data = {
        "version": "1.0",
        "tenant_id": tenant_id,
        "api_key_env": "AGENTMESH_API_KEY",
        "endpoint": endpoint,
        "framework": framework,
        "tools": {
            "audit_log_action": True,
            "verify_agent_identity": True,
            "evaluate_policy": True,
        },
        "guardrails": {
            "prompt_injection_detection": True,
            "dlp_scanning": False,
        },
        "trust": {
            "enabled": True,
            "decay_half_life_hours": 168,
            "circuit_breaker_threshold": 3,
        },
        "bft": {
            "enabled": False,
            "quorum_size": 4,
        },
    }
    with open(config_path, "w") as f:
        yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)
    click.echo(click.style("  [config] ", fg="green") + f"Created {_CONFIG_FILENAME}")

    # ---- Step 6: generate middleware file ----
    filename, template = _TEMPLATES[framework]
    middleware_path = Path(filename)
    if middleware_path.exists():
        if not click.confirm(f"  {filename} already exists. Overwrite?", default=False):
            click.echo(f"  Skipped {filename}.")
        else:
            middleware_path.write_text(template)
            click.echo(click.style("  [code]   ", fg="green") + f"Created {filename}")
    else:
        middleware_path.write_text(template)
        click.echo(click.style("  [code]   ", fg="green") + f"Created {filename}")

    # ---- Step 7: suggest .env ----
    env_path = Path(".env")
    if env_path.exists():
        env_content = env_path.read_text()
        if "AGENTMESH_API_KEY" not in env_content:
            click.echo(click.style("  [hint]   ", fg="yellow") + f"Add to .env: AGENTMESH_API_KEY={api_key}")
    else:
        click.echo(click.style("  [hint]   ", fg="yellow") + f"Set env var: export AGENTMESH_API_KEY={api_key}")

    # ---- Step 8: print next steps ----
    click.echo()
    click.secho("  --- Next Steps ---", fg="cyan", bold=True)
    click.echo()

    if framework == "crewai":
        click.echo("  1. Import the middleware in your crew file:")
        click.echo(click.style("     from agentmesh_middleware import compliant_crew", fg="white"))
        click.echo()
        click.echo("  2. Wrap your crew:")
        click.echo(click.style("     crew = compliant_crew(MyCrew())", fg="white"))
        click.echo(click.style("     result = crew.kickoff()", fg="white"))
    elif framework == "langgraph":
        click.echo("  1. Import the middleware in your graph file:")
        click.echo(click.style("     from agentmesh_middleware import compliant_graph", fg="white"))
        click.echo()
        click.echo("  2. Wrap your compiled graph:")
        click.echo(click.style("     graph = compliant_graph(my_graph.compile())", fg="white"))
        click.echo(click.style("     result = graph.invoke(input)", fg="white"))
    elif framework == "autogen":
        click.echo("  1. Import the middleware:")
        click.echo(click.style("     from agentmesh_middleware import compliant_chat", fg="white"))
        click.echo()
        click.echo("  2. Wrap your group chat:")
        click.echo(click.style("     chat = compliant_chat(my_group_chat)", fg="white"))
    else:
        click.echo("  1. Import the client:")
        click.echo(click.style("     from agentmesh_mcp_client import get_client", fg="white"))
        click.echo()
        click.echo("  2. Use it:")
        click.echo(click.style('     client = get_client()', fg="white"))
        click.echo(click.style('     client.verify_agent_identity_sync("my-agent", "researcher")', fg="white"))

    click.echo()
    click.echo("  3. Run " + click.style("agentmesh status", fg="cyan") + " to verify your setup")
    click.echo("  4. View your dashboard at " + click.style("https://app.useagentmesh.com/dashboard", fg="cyan", underline=True))
    click.echo()
